### ISSUE TITLE
Any way to override nodes etcd-test/register-test run on?

### ISSUE THREAD

**Issue by jlamillan** [jepsen-io/jepsen#161]
Greetings.  I'm trying to figure out if there is a straightforward way to override the etcd nodes the etcd-test/register-test run against. I think I am looking for something similar to the `--nodes-file` option `jepsen.cli/single-test-cmd` provides, but I see the test is not set up to run that way.

Any help would be appreciated - I am very new to Jepsen.

**Comment by aphyr** [comment]
You can either port the test to use the jepsen.cli runner, or add a `:nodes` key to the test map directly.

**Comment by jlamillan** [comment]
Perfect, thank you Kyle.
