### ISSUE TITLE
Tests development workflow

### ISSUE THREAD

**Issue by seahckr** [jepsen-io/jepsen#162]
This isn't an issue with Jepsen, but I was hoping somebody can help a Clojure newbie here :) I'm trying to write some tests, but also change a bit of Jepsen code while doing it. Since my tests have a dependency on jepsen (which is a separate module), what is the best development workflow here? Is there a way to "hot reload" dependent modules? Thanks!

**Comment by aphyr** [comment]
I believe (require 'jepsen.whatever-ns-you-changed :reload-all) should do the trick.

**Comment by seahckr** [comment]
Thanks! This in addition with the checkouts functionality gives what I was looking for
