### ISSUE TITLE
Why is this flagged as a CAS Register Consistency Violation?

### ISSUE THREAD

**Issue by seahckr** [jepsen-io/jepsen#164]
![image](https://cloud.githubusercontent.com/assets/20646041/23003447/c3ecbb44-f3a5-11e6-8155-03c8e87b147d.png)

I am writing a simple test against my system - and found that the model checker is flagging this. Why? Please help me understand.. It looks like I can explain these operations like so:

Write 3
Read 3
Read 3
Read 3
Write 0

**Comment by aphyr** [comment]
`["id" 3]` and `3` are not the same value.
