### ISSUE TITLE
Testing without SSH

### ISSUE THREAD

**Issue by dricketts** [jepsen-io/jepsen#167]
I have a test setup in which each node in my system runs as a separate process rather than on a separate machine. Can I run a Jepsen test in this scenario, i.e. without SSH? It seems that I would need to do the following:

- Provide an implementation of the Net interface to inject faults
- Use something other than the functions in jepsen.control to create the DBs

Is there something else that relies on SSH?

**Comment by seahckr** [comment]
I am also interested in the answer to this question.

**Comment by aphyr** [comment]
Yeah, I think you can use an empty node list, and Jepsen won't open any SSH connections. But then it's not gonna know how to handle setup and clients, so you'll need to figure out your own ways of handling that. Probably involves gutting jepsen.core/run-test.

**Comment by dricketts** [comment]
An empty node list does work. Another approach is a node list of one element [:localhost]. Then you should be able to use the setup and teardown functionality of db. However, I can't seem to get this to work, as I keep getting com.jcraft.jsch.JSchException: Auth fail ...

**Comment by aphyr** [comment]
Yeah you'll need SSH credentials for localhost for that to workOr, you know, use containers. Probably faster than trying to write your own network and setup code.On Mar 24, 2017 5:43 PM, dricketts <notifications@github.com> wrote:An empty node list does work. Another approach is a node list of one element [:localhost]. Then you should be able to use the setup and teardown functionality of db. However, I can't seem to get this to work, as I keep getting com.jcraft.jsch.JSchException: Auth fail ...

**Comment by dricketts** [comment]
I had SSH credentials set up, but for some reason, the command line
arguments for my username and key file weren't having any effect. Passing
these values within Clojure solved the problem. Not sure what the issue was
with command line arguments, but I was most likely just being dumb.
