### ISSUE TITLE
No ~/.ssh/known_hosts

### ISSUE THREAD

**Issue by UncP** [jepsen-io/jepsen#185]
I followed the instructions in README but when i run

> lein test

in aerospike

it shows that

> ERROR in (counter) (KnownHosts.java:63)
> Uncaught exception, not in assertion.
> expected: nil
>   actual: com.jcraft.jsch.JSchException: java.io.FileNotFoundException: /root/.ssh/known_hosts (没有那个文件或目录)
>  at com.jcraft.jsch.KnownHosts.setKnownHosts (KnownHosts.java:63)
>     com.jcraft.jsch.JSch.setKnownHosts (JSch.java:303)
>     clj_ssh.ssh$ssh_agent$fn__5953.invoke (ssh.clj:151)
>     clj_ssh.ssh$ssh_agent.invoke (ssh.clj:150)
>     jepsen.control$session.invoke (control.clj:193)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.AFn.applyTo (AFn.java:144)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.core$with_bindings_STAR_.doInvoke (core.clj:1862)
>     clojure.lang.RestFn.applyTo (RestFn.java:142)
>     clojure.core$apply.invoke (core.clj:628)
>     clojure.core$bound_fn_STAR_$fn__4140.doInvoke (core.clj:1884)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invoke (core.clj:624)
>     jepsen.core$fcatch$wrapper__7453.doInvoke (core.clj:53)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.core$pmap$fn__6328$fn__6329.invoke (core.clj:6466)
>     clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
>     clojure.lang.AFn.call (AFn.java:18)
>     java.util.concurrent.FutureTask.run (FutureTask.java:266)
>     java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
>     java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
>     java.lang.Thread.run (Thread.java:748)
> Caused by: java.io.FileNotFoundException: /root/.ssh/known_hosts (没有那个文件或目录)
>  at java.io.FileInputStream.open0 (FileInputStream.java:-2)
>     java.io.FileInputStream.open (FileInputStream.java:195)
>     java.io.FileInputStream.<init> (FileInputStream.java:138)
>     java.io.FileInputStream.<init> (FileInputStream.java:93)
>     com.jcraft.jsch.KnownHosts.setKnownHosts (KnownHosts.java:59)
>     com.jcraft.jsch.JSch.setKnownHosts (JSch.java:303)
>     clj_ssh.ssh$ssh_agent$fn__5953.invoke (ssh.clj:151)
>     clj_ssh.ssh$ssh_agent.invoke (ssh.clj:150)
>     jepsen.control$session.invoke (control.clj:193)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.AFn.applyTo (AFn.java:144)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.core$with_bindings_STAR_.doInvoke (core.clj:1862)
>     clojure.lang.RestFn.applyTo (RestFn.java:142)
>     clojure.core$apply.invoke (core.clj:628)
>     clojure.core$bound_fn_STAR_$fn__4140.doInvoke (core.clj:1884)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invoke (core.clj:624)
>     jepsen.core$fcatch$wrapper__7453.doInvoke (core.clj:53)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.core$pmap$fn__6328$fn__6329.invoke (core.clj:6466)
>     clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
>     clojure.lang.AFn.call (AFn.java:18)
>     java.util.concurrent.FutureTask.run (FutureTask.java:266)
>     java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
>     java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
>     java.lang.Thread.run (Thread.java:748)
> 
> lein test :only aerospike.core-test/cas-register
> 
> ERROR in (cas-register) (KnownHosts.java:63)
> Uncaught exception, not in assertion.
> expected: nil
>   actual: com.jcraft.jsch.JSchException: java.io.FileNotFoundException: /root/.ssh/known_hosts (没有那个文件或目录)
>  at com.jcraft.jsch.KnownHosts.setKnownHosts (KnownHosts.java:63)
>     com.jcraft.jsch.JSch.setKnownHosts (JSch.java:303)
>     clj_ssh.ssh$ssh_agent$fn__5953.invoke (ssh.clj:151)
>     clj_ssh.ssh$ssh_agent.invoke (ssh.clj:150)
>     jepsen.control$session.invoke (control.clj:193)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.AFn.applyTo (AFn.java:144)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.core$with_bindings_STAR_.doInvoke (core.clj:1862)
>     clojure.lang.RestFn.applyTo (RestFn.java:142)
>     clojure.core$apply.invoke (core.clj:628)
>     clojure.core$bound_fn_STAR_$fn__4140.doInvoke (core.clj:1884)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invoke (core.clj:624)
>     jepsen.core$fcatch$wrapper__7453.doInvoke (core.clj:53)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.core$pmap$fn__6328$fn__6329.invoke (core.clj:6466)
>     clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
>     clojure.lang.AFn.call (AFn.java:18)
>     java.util.concurrent.FutureTask.run (FutureTask.java:266)
>     java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
>     java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
>     java.lang.Thread.run (Thread.java:748)
> Caused by: java.io.FileNotFoundException: /root/.ssh/known_hosts (没有那个文件或目录)
>  at java.io.FileInputStream.open0 (FileInputStream.java:-2)
>     java.io.FileInputStream.open (FileInputStream.java:195)
>     java.io.FileInputStream.<init> (FileInputStream.java:138)
>     java.io.FileInputStream.<init> (FileInputStream.java:93)
>     com.jcraft.jsch.KnownHosts.setKnownHosts (KnownHosts.java:59)
>     com.jcraft.jsch.JSch.setKnownHosts (JSch.java:303)
>     clj_ssh.ssh$ssh_agent$fn__5953.invoke (ssh.clj:151)
>     clj_ssh.ssh$ssh_agent.invoke (ssh.clj:150)
>     jepsen.control$session.invoke (control.clj:193)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.AFn.applyTo (AFn.java:144)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.core$with_bindings_STAR_.doInvoke (core.clj:1862)
>     clojure.lang.RestFn.applyTo (RestFn.java:142)
>     clojure.core$apply.invoke (core.clj:628)
>     clojure.core$bound_fn_STAR_$fn__4140.doInvoke (core.clj:1884)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invoke (core.clj:624)
>     jepsen.core$fcatch$wrapper__7453.doInvoke (core.clj:53)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.core$pmap$fn__6328$fn__6329.invoke (core.clj:6466)
>     clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
>     clojure.lang.AFn.call (AFn.java:18)
>     java.util.concurrent.FutureTask.run (FutureTask.java:266)
>     java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
>     java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
>     java.lang.Thread.run (Thread.java:748)
> 
> Ran 2 tests containing 2 assertions.
> 0 failures, 2 errors.
> Tests failed.
> 

the Chinese means that there is no file ~/.ssh/known_hosts.

I tried create ~/.ssh/known_hosts and type

> ssh-keyscan -t rsa n1 >> ~/.ssh/known_hosts
> ssh-keyscan -t rsa n2 >> ~/.ssh/known_hosts
> ssh-keyscan -t rsa n3 >> ~/.ssh/known_hosts
> ssh-keyscan -t rsa n4 >> ~/.ssh/known_hosts
> ssh-keyscan -t rsa n5 >> ~/.ssh/known_hosts 

but get this
> ERROR in (counter) (Util.java:349)
> Uncaught exception, not in assertion.
> expected: nil
>   actual: com.jcraft.jsch.JSchException: java.net.UnknownHostException: n1
>  at com.jcraft.jsch.Util.createSocket (Util.java:349)
>     com.jcraft.jsch.Session.connect (Session.java:215)
>     com.jcraft.jsch.Session.connect (Session.java:183)
>     clj_ssh.ssh$eval5939$fn__5946.invoke (ssh.clj:118)
>     clj_ssh.ssh.protocols$eval5865$fn__5888$G__5856__5897.invoke (protocols.clj:4)
>     clj_ssh.ssh$connect.invoke (ssh.clj:401)
>     jepsen.control$session.invoke (control.clj:197)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.AFn.applyTo (AFn.java:144)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.core$with_bindings_STAR_.doInvoke (core.clj:1862)
>     clojure.lang.RestFn.applyTo (RestFn.java:142)
>     clojure.core$apply.invoke (core.clj:628)
>     clojure.core$bound_fn_STAR_$fn__4140.doInvoke (core.clj:1884)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invoke (core.clj:624)
>     jepsen.core$fcatch$wrapper__7453.doInvoke (core.clj:53)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.core$pmap$fn__6328$fn__6329.invoke (core.clj:6466)
>     clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
>     clojure.lang.AFn.call (AFn.java:18)
>     java.util.concurrent.FutureTask.run (FutureTask.java:266)
>     java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
>     java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
>     java.lang.Thread.run (Thread.java:748)
> Caused by: java.net.UnknownHostException: n1
>  at java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:184)
>     java.net.SocksSocketImpl.connect (SocksSocketImpl.java:392)
>     java.net.Socket.connect (Socket.java:589)
>     java.net.Socket.connect (Socket.java:538)
>     java.net.Socket.<init> (Socket.java:434)
>     java.net.Socket.<init> (Socket.java:211)
>     com.jcraft.jsch.Util.createSocket (Util.java:343)
>     com.jcraft.jsch.Session.connect (Session.java:215)
>     com.jcraft.jsch.Session.connect (Session.java:183)
>     clj_ssh.ssh$eval5939$fn__5946.invoke (ssh.clj:118)
>     clj_ssh.ssh.protocols$eval5865$fn__5888$G__5856__5897.invoke (protocols.clj:4)
>     clj_ssh.ssh$connect.invoke (ssh.clj:401)
>     jepsen.control$session.invoke (control.clj:197)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.AFn.applyTo (AFn.java:144)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.core$with_bindings_STAR_.doInvoke (core.clj:1862)
>     clojure.lang.RestFn.applyTo (RestFn.java:142)
>     clojure.core$apply.invoke (core.clj:628)
>     clojure.core$bound_fn_STAR_$fn__4140.doInvoke (core.clj:1884)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invoke (core.clj:624)
>     jepsen.core$fcatch$wrapper__7453.doInvoke (core.clj:53)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.core$pmap$fn__6328$fn__6329.invoke (core.clj:6466)
>     clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
>     clojure.lang.AFn.call (AFn.java:18)
>     java.util.concurrent.FutureTask.run (FutureTask.java:266)
>     java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
>     java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
>     java.lang.Thread.run (Thread.java:748)
> 
> lein test :only aerospike.core-test/cas-register
> 
> ERROR in (cas-register) (Util.java:349)
> Uncaught exception, not in assertion.
> expected: nil
>   actual: com.jcraft.jsch.JSchException: java.net.UnknownHostException: n1
>  at com.jcraft.jsch.Util.createSocket (Util.java:349)
>     com.jcraft.jsch.Session.connect (Session.java:215)
>     com.jcraft.jsch.Session.connect (Session.java:183)
>     clj_ssh.ssh$eval5939$fn__5946.invoke (ssh.clj:118)
>     clj_ssh.ssh.protocols$eval5865$fn__5888$G__5856__5897.invoke (protocols.clj:4)
>     clj_ssh.ssh$connect.invoke (ssh.clj:401)
>     jepsen.control$session.invoke (control.clj:197)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.AFn.applyTo (AFn.java:144)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.core$with_bindings_STAR_.doInvoke (core.clj:1862)
>     clojure.lang.RestFn.applyTo (RestFn.java:142)
>     clojure.core$apply.invoke (core.clj:628)
>     clojure.core$bound_fn_STAR_$fn__4140.doInvoke (core.clj:1884)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invoke (core.clj:624)
>     jepsen.core$fcatch$wrapper__7453.doInvoke (core.clj:53)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.core$pmap$fn__6328$fn__6329.invoke (core.clj:6466)
>     clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
>     clojure.lang.AFn.call (AFn.java:18)
>     java.util.concurrent.FutureTask.run (FutureTask.java:266)
>     java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
>     java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
>     java.lang.Thread.run (Thread.java:748)
> Caused by: java.net.UnknownHostException: n1
>  at java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:184)
>     java.net.SocksSocketImpl.connect (SocksSocketImpl.java:392)
>     java.net.Socket.connect (Socket.java:589)
>     java.net.Socket.connect (Socket.java:538)
>     java.net.Socket.<init> (Socket.java:434)
>     java.net.Socket.<init> (Socket.java:211)
>     com.jcraft.jsch.Util.createSocket (Util.java:343)
>     com.jcraft.jsch.Session.connect (Session.java:215)
>     com.jcraft.jsch.Session.connect (Session.java:183)
>     clj_ssh.ssh$eval5939$fn__5946.invoke (ssh.clj:118)
>     clj_ssh.ssh.protocols$eval5865$fn__5888$G__5856__5897.invoke (protocols.clj:4)
>     clj_ssh.ssh$connect.invoke (ssh.clj:401)
>     jepsen.control$session.invoke (control.clj:197)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.AFn.applyTo (AFn.java:144)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.core$with_bindings_STAR_.doInvoke (core.clj:1862)
>     clojure.lang.RestFn.applyTo (RestFn.java:142)
>     clojure.core$apply.invoke (core.clj:628)
>     clojure.core$bound_fn_STAR_$fn__4140.doInvoke (core.clj:1884)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invoke (core.clj:624)
>     jepsen.core$fcatch$wrapper__7453.doInvoke (core.clj:53)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.core$pmap$fn__6328$fn__6329.invoke (core.clj:6466)
>     clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
>     clojure.lang.AFn.call (AFn.java:18)
>     java.util.concurrent.FutureTask.run (FutureTask.java:266)
>     java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
>     java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
>     java.lang.Thread.run (Thread.java:748)
> 
> Ran 2 tests containing 2 assertions.
> 0 failures, 2 errors.
> Tests failed.
> 

i wondered what's wrong with ~/.ssh/known_hosts, what i should do with it.

**Comment by aphyr** [comment]
```
java.net.UnknownHostException: n1
```

Like the exception says, you don't have a host called `n1` resolvable.

**Comment by UncP** [comment]
So I should first create ~/.ssh/known_hosts, then add host that is resolvable?

i am wondering how can i run `lein test` on `aerospike` on my computer--a single node? In this situation how do i modify ~/.ssh/known_hosts?

If i run `lein test` on `aerospike` on multi-nodes, how do i modify ~/.ssh/known_hosts?

**Comment by vjuranek** [comment]
Hi,
modifying `~/.ssh/known_hosts` is useless here. If you want to run tests on you local machine only, you need to start appropriate number (by default 5) VMs or containers on a local machine and eventually modify your `/etc/resolv.conf`so that machine names (by default `n1`, ..., `n5`) are resolvable from your localhost (from which you run the tests). I'd recommend to read [this howto](https://github.com/jepsen-io/jepsen/blob/master/doc/lxc.md), or, even better, if you are not familiar with LXC, use docker compose prepared in [docker directory](https://github.com/jepsen-io/jepsen/tree/master/docker) (and of course install and start docker daemon if you haven't done it already). It's as simple as runing
* `./up.sh` in docker dir
* `docker exec -it jepsen-control bash` in new terminal window
* `cd aerospike && lein test` in the terminal mention in above step

**Comment by UncP** [comment]
Thanks for your reply! I tried the `docker` method but it won'y work.

![1](https://user-images.githubusercontent.com/16263931/28112030-1f1986c6-672a-11e7-9cbf-34dff885ad91.png)

in the up picture the websites does not exist any more.

![2](https://user-images.githubusercontent.com/16263931/28112035-26cbe85a-672a-11e7-9fb5-0f120809b906.png)

in the up picture it suggests that i add `--force-yes` in the command.

does this mean that the docker method is a no go and i should use lxc instead?

**Comment by vjuranek** [comment]
I'm not Debian expert, but I'd say that following has happened: it failed to resolved Debian geo mirroring, which is probably some issue on your ISP side. Therefore it failed to download gpg keys and failed to verify some packages to be installed. As a temporal workaround (until you find out why some Debian DNSs cannot be resolved), you can try to append `--force-yes` after `apt-get install -y` in [node docker file, like 4](https://github.com/jepsen-io/jepsen/blob/master/docker/node/Dockerfile#L4) and in  [control docker file, like 13](https://github.com/jepsen-io/jepsen/blob/master/docker/control/Dockerfile#L13)

**Comment by kaibimouez** [comment]
Hello @aphyr ,
i have the same error : Caused by: java.net.UnknownHostException: n1
Can you help me please.
thank you very much
