### ISSUE TITLE
Running docker/up.sh failed?

### ISSUE THREAD

**Issue by UncP** [jepsen-io/jepsen#186]
i ran doceker/up.sh on ubuntu 16.04, it failed at step 4/11when building control.

![1](https://user-images.githubusercontent.com/16263931/28157549-7355ec88-67e9-11e7-91b1-ea1964c7e300.png)

it seems that `reading package lists` never proceed, i tried a few times running `up.sh` but it just stops there.

**Comment by aphyr** [comment]
Sorry, I don't know how docker works, but you're welcome to ask the author or poke around and submit a patch. The easiest way for you to get started is probably to use the AWS cluster, where everything's prebuilt for you. Try https://aws.amazon.com/marketplace/pp/B01LZ7Y7U0?qid=1486758124485&sr=0-1&ref_=srh_res_product_title, and use "5+1 cluster" for delivery.

**Comment by UncP** [comment]
i did some google and re-ran this shell and it worked, thanks any way.
