### ISSUE TITLE
cockroachdb nemesis 'slow' error

### ISSUE THREAD

**Issue by UncP** [jepsen-io/jepsen#191]
in runner.clj line 53:

> "slow" (cln/slow 250)

this is the line that generates `slow` nemesis, cln stands for jepsen.cockroach.nemesis.
but in nemesis.clj, theis no `slow` function, but `slowing`, also `slowing` takes 2 args.

how can i use `slow` nemesis?

**Comment by aphyr** [comment]
Ah, that's a holdover from an earlier experiment that I forgot to clean up. Slow isn't it's own nemesis; it's built into others like big-skews and huge-skews. If you look at the uses of `slowing` in that file you'll see where it's used. I've removed the unused slow nemesis from the CLI.
