### ISSUE TITLE
register test out of memeory

### ISSUE THREAD

**Issue by UncP** [jepsen-io/jepsen#195]
when verifying linearizability, it says out of memory even i only ran the test for 60 seconds, the model is knossos.casregister, is it the problem of nemsis? I add majority-ring the same in cockroachdb.

**Comment by ivankelly** [comment]
I've seen similar problems, I think mostly because I was trying very log runs with a lot of operations.
How much memory/cpu does the machine have?
How many operations are there in the history?

**Comment by aphyr** [comment]
Verification complexity depends mostly on the concurrency of the test. All else being equal, the search is linear in history length, and exponential in concurrency. The more degeneracy/commutativity in the model, the less state Knossos has to maintain. Other than that, I can't really tell you what's going on. It'll depend on the structure of your history, and that depends on your test structure and semantics.

**Comment by aphyr** [comment]
I should note that if you haven't yet read the tutorial in the doc/ directory, there's a section there that talks extensively about knossos performance and some common pitfalls/fixes to be aware of. Might be worth a look.
