### ISSUE TITLE
Example history sizes and processing times in FAQ

### ISSUE THREAD

**Issue by ivankelly** [jepsen-io/jepsen#198]
It's not immediately obvious when poking around that it's the analysis and not the test itself that does the heavy lifting.  It would be useful to have the running times for the linearable analysis for different history lengths and models. It wouldn't have to be in any way exhaustive, but something that said something like:
- 200 element history, cas-register-model, 48 core/128GB, 5 minutes
- 300 element history, cas-register-model, 48 core/128GB, 12 hours

I think the FAQ would be the best place.

**Comment by aphyr** [comment]
I can't give you any sort of meaningful numbers; it's an NP-hard problem with extremely sensitive dependence on model semantics, concurrency, and commutativity. A hundred-element history could take weeks to verify, and a million-element history might go by in a few seconds. Often, histories from the same test will take wildly varying times to check.
