### ISSUE TITLE
Does client run in control node?

### ISSUE THREAD

**Issue by skillness** [jepsen-io/jepsen#202]
Thanks for your work on jepsen.
I have a question about it.
I want to know if I use a client to connect to a distributed database for testing, is this client just run in control node?
If the client just run in control node with multi-thread or multi-process, what is the meaning of --concurrency?

**Comment by aphyr** [comment]
All clients are run in the same JVM on the control node, and --concurrency controls the number of concurrent clients/workers.On Oct 15, 2017 04:05, skillness <notifications@github.com> wrote:Thanks for your work on jepsen.
I have a question about it.
I want to know if I use a client to connect to a distributed database for testing, is this client just run in control node?
If the client just run in control node with multi-thread or multi-process, what is the meaning of --concurrency?

**Comment by skillness** [comment]
Thank you so much!
