### ISSUE TITLE
Zookeeper can not pass tests?

### ISSUE THREAD

**Issue by gaodq** [jepsen-io/jepsen#204]
I have tried testing zookeeper using jepsen, but I have got a failed result.
This zookeeper version has passed this test, doesn't it?
Here is my result and history file.
[20171014T161015.zip](https://github.com/jepsen-io/jepsen/files/1386847/20171014T161015.zip)

**Comment by aphyr** [comment]
Yep, this is a nonlinearizable result, but if you look at the logs, you'll see that the Zookeeper cluster never formed. That's why no two nodes agree.
