### ISSUE TITLE
generator/void makes the Fressian throw exception

### ISSUE THREAD

**Issue by yyh-graphsql** [jepsen-io/jepsen#208]
Hi, I'm using jepsen 0.1.4 for testing.

I first used a generator/void as the nemesis generator. But after the testing finished. It got the following exception. The jepsen.generator$reify__4129@2a4f5433 I checked is the generator/void's reify object.

> Caused by: java.lang.IllegalArgumentException: Cannot write jepsen.generator$reify__4129@2a4f5433 as tag null
>   at org.fressian.handlers.WriteHandlerLookup.requireWriteHandler(WriteHandlerLookup.java:48) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeAs(FressianWriter.java:458) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeAs(FressianWriter.java:464) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeObject(FressianWriter.java:472) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeIterator(FressianWriter.java:152) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeList(FressianWriter.java:165) ~[fressian-0.6.6.jar:na]
>   at org.fressian.impl.Handlers$32.write(Handlers.java:352) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.doWrite(FressianWriter.java:449) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeAs(FressianWriter.java:459) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeAs(FressianWriter.java:464) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeObject(FressianWriter.java:472) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeIterator(FressianWriter.java:152) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeList(FressianWriter.java:165) ~[fressian-0.6.6.jar:na]
>   at org.fressian.impl.Handlers$29.write(Handlers.java:323) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.doWrite(FressianWriter.java:449) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeAs(FressianWriter.java:459) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeAs(FressianWriter.java:464) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeObject(FressianWriter.java:472) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeIterator(FressianWriter.java:152) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeList(FressianWriter.java:165) ~[fressian-0.6.6.jar:na]
>   at org.fressian.impl.Handlers$32.write(Handlers.java:352) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.doWrite(FressianWriter.java:449) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeAs(FressianWriter.java:459) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeAs(FressianWriter.java:464) ~[fressian-0.6.6.jar:na]
>   at org.fressian.FressianWriter.writeObject(FressianWriter.java:472) ~[fressian-0.6.6.jar:na]
>   at clojure.data.fressian$write_object.invokeStatic(fressian.clj:219) ~[jepsen-0.1.5.jar:na]
>   at clojure.data.fressian$write_object.invoke(fressian.clj:216) ~[jepsen-0.1.5.jar:na]
>   at jepsen.store$write_fressian_BANG_.invokeStatic(store.clj:270) ~[jepsen-0.1.5.jar:na]
>   at jepsen.store$write_fressian_BANG_.invoke(store.clj:264) ~[jepsen-0.1.5.jar:na]
>   at jepsen.store$save_1_BANG_$fn__4720.invoke(store.clj:279) ~[jepsen-0.1.5.jar:na]
>   at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) ~[clojure-1.8.0.jar:na]
>   at clojure.lang.AFn.call(AFn.java:18) [clojure-1.8.0.jar:na]
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_144]
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_144]
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_144]
>   at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]

Can anyone take a look at this problem?

Thanks,
Yihao

**Comment by aphyr** [comment]
Yihao, could you post your test please? Without seeing the code I can't really tell what's going on.

**Comment by yyh-graphsql** [comment]
```
; default nemesis
(def noop
  "No failure."
  {
    :name "Noop"
    :during gen/void
    :final  gen/void
    :client nemesis/noop
  })

; default client
(defn base-test
    "Return Base test parameters which will be overridden by other tests."
  [opts]
  (let [ new-opts (merge tests/noop-test
                         {:name          "BaseTest"
                          ;agent node is the node to run gadmin command
                          :agent-node    "m1"
                          :db            (db/db (assoc opts :agent-node "m1"))
                          :nemesis       (:client (:nemesis opts))
                          :client        (:client (:client opts))
                          :generator     (gen/phases
                                           (->> (gen/nemesis (:during (:nemesis opts))
                                                             (:during (:client opts)))
                                                (gen/time-limit (:time-limit opts)))
                                           (gen/log "Terminating Nemesis")
                                           (gen/nemesis (:final (:nemesis opts)))
                                           (gen/log "Recovering Clients")
                                           (gen/sleep (:recovery-time opts))
                                           (gen/clients (:final (:client opts)))
                                         )
                         }
                         (dissoc opts :client :nemesis))]
    (info "Client:\n" (type new-opts))
    (info "Transfered TestOptions:\n" (with-out-str (pprint new-opts)))
    new-opts
  )
)
(defn test
  [opts]
  (base-test
    (merge
      {
        :name       "Vertex-R/W/D"
        :client     {
                      :client (VertexOpClient. nil 1000)
                      :during (->> (gen/mix
                                     [write-vertex
                                      read-vertex read-vertex
                                      delete-vertex delete-vertex])
                                   (gen/stagger 0))
                      :final (gen/once (count-vertex))
                    }
        :checker    (checker/compose
                      {
                        :perf (checker/perf)
                        :timeline (timeline/html)
                        ;:vertex (checker/unbridled-optimism) ;TODO(yihao) comment temporily for some is wrong.
                      }
                    )
        :model      model/noop ;TODO(yihao)
      }
      opts
    )
  )
)

(def tiger-opt-spec
  "Command line options for tools.cli"
  [
    jc/help-opt

    (jc/repeated-opt "-n" "--node HOSTNAME" "Node(s) to run test on"
                  ["m1", "m2", "m3"])

    [nil "--nodes-file FILENAME" "File containing node hostnames, one per line."]

    [nil "--username USER" "Username for logins"
     :default "tiger"]

    [nil "--password PASS" "Password for sudo access"
     :default "tiger"]

    [nil "--strict-host-key-checking" "Whether to check host keys"
     :default false]

    [nil "--ssh-private-key FILE" "Path to an SSH identity file"]

    [nil "--concurrency NUMBER" "How many workers should we run? Must be an integer, optionally followed by n (e.g. 3n) to multiply by the number of nodes."
     :default  "3n"
     :validate [(partial re-find #"^\d+n?$")
                "Must be an integer, optionally followed by n."]]

    (jc/repeated-opt "-t" "--test-suite NAME" "Test(s) to run" [test] supported-test-suites)

    [nil "--test-count NUMBER"
     "How many times should we repeat a test?"
     :default  1
     :parse-fn #(Long/parseLong %)
     :validate [pos? "Must be positive"]]

    [nil "--time-limit SECONDS"
     "Excluding setup and teardown, how long should a test run for, in seconds?"
     :default  60
     :parse-fn #(Long/parseLong %)
     :validate [pos? "Must be positive"]]

    [nil "--recovery-time SECONDS"
     "How long to wait for cluster recovery before final client ops."
     :default 60
     :parse-fn #(Long/parseLong %)
     :validate [pos? "Must be positive"]]

    (jc/repeated-opt nil "--failure NAME" "Which failure to use"
                     [noop]
                     supported-failures)

    ["-o" "--os NAME" "debian, or none"
     :default  os/noop
     :parse-fn supported-oses
     :validate [identity (jc/one-of supported-oses)]]
  ]
)

(defn command-descriptor
  "Command description table for tiger HA & Consistency tests."
  []
  (reduce merge
    [
      {"test" {
                :opt-spec tiger-opt-spec
                :opt-fn   jc/test-opt-fn
                :run      (fn [{:keys [options]}]
                            (info "Test options:\n"
                                  (with-out-str (pprint options)))
                            (doseq [i       (range (:test-count options))
                                    test-fn (:test-suite options)
                                    nemesis (:failure options)]
                              (let [test (jepsen/run!
                                           (test-fn (assoc options :nemesis nemesis)))]
                                (when-not (:valid? (:results test))
                                  (System/exit 1)
                                )
                              )
                            )
                          )
              }
      },
      ; add more command here
      { }
    ]
  )
)

(defn -main
  [& args]
  (jc/run! (merge (jc/serve-cmd)
                  (command-descriptor))
           args
  )
)
```

Hi, aphyr

I posted some code snippets above. Is this enough for you?

Thanks,
yihao

**Comment by aphyr** [comment]
You've added a new key to the test, `:failure`, containing an object `(gen/void)` that can't be serialized. Add `:failure` to the test's `:nonserializable-keys`.
