### ISSUE TITLE
how to do node setup for etcd tutorial ?

### ISSUE THREAD

**Issue by ashishnegi** [jepsen-io/jepsen#240]
Hi
Thanks for this great practical project.
I am going through the [tutorial](https://github.com/jepsen-io/jepsen/blob/master/doc/tutorial/index.md).

I created a local project as mentioned but running the `lein run test` command gave me errors that nodes are not setup properly.

What is the right setup for the tutorial to work ?

I followed the docker page and from inside `jepsen-control` container, the tutorial is working. 
But since its container, any changes done are not saved. 

What is the strategy for going through the tutorial effectively ?

**Comment by aphyr** [comment]
You can use docker, vagrant, AWS, physical nodes, VMs... whatever's convenient for you. I develop locally on regular LXC containers, and use AWS for most tests, syncing my repos locally with rsync. Docker seems to be a viable option, though I haven't used it myself, so I can't really advise you on how to do persistence. I imagine there's some sort of mountable directory, or you could use git, rsync, or something like that.
