### ISSUE TITLE
how to using the local jar of jepsen with lein?

### ISSUE THREAD

**Issue by Leviathan1995** [jepsen-io/jepsen#248]
@aphyr Hi, I support the centos for jepsen, and  need to test this version with etcd now. I already 
 use `lein uberjar` to package the modified version of jepsen as `.jar`, but while I use `lein run test` that will automatic download the offical `0.1.9-SNAPSHOT` version of jepsen.

#### project.clj:
```
(defproject jepsen.etcd "0.1.0-SNAPSHOT"
  :description "A Jepsen test for etcd"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :main jepsen.etcd
  :jvm-opts ["-Dcom.sun.management.jmxremote"]
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [jepsen "0.1.9-SNAPSHOT"]
                 [verschlimmbesserung "0.1.3"]])
```

**Comment by aphyr** [comment]
Sorry, I'm not sure I understand your question. Are you asking how to install Jepsen locally for testing? Use `lein install`. You may also want to try checkouts: https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#checkout-dependencies

**Comment by Leviathan1995** [comment]
@aphyr Thanks, I solved this problem!
