### ISSUE TITLE
Are there any jepsen tests which are really testing against slow/flaky network and duplicate packets? 

### ISSUE THREAD

**Issue by ttyusupov** [jepsen-io/jepsen#254]
Are there any jepsen tests which are really testing against slow/flaky network and duplicate packets? I have found examples of using network partition nemeses for various DBs, but are there any DB which has jepsen tests utilizing slow/flaky network faults (implemented in jepsen/jepsen/src/jepsen/net.clj) ? 
Also I can't find packet duplication fault implementation in jepsen framework, does anyone test it?

**Comment by aphyr** [comment]
Almost every system we test uses TCP, which tends to turn slow/duplicate/dropped packets into plain old stream latency. None of the tests where I've experimented with packet loss or reorderings have found anything.
