### ISSUE TITLE
Is this an non linearizable result?

### ISSUE THREAD

**Issue by leviathan0992** [jepsen-io/jepsen#257]
@aphyr I use Jepsen to test my system and got a non-linearizable result, but I don't know why it's not accord with the linearizable algorithm：
![Imgur](https://i.imgur.com/woKpaqR.png)

**Comment by aphyr** [comment]
Process 7 read the value 4 when the only possible states at that time were 2 or 3.

**Comment by Leviathan1995** [comment]
@aphyr  I use the red lines to draw linearization points for all operations. Maybe I misunderstanding the linearizable algorithm, please explain this for me. thank you!

![Imgur](https://i.imgur.com/906NsQd.png)

**Comment by aphyr** [comment]
This is A Long Discussion, but the tl;dr is that you have to start with `read 2`. If you go stare at the raw history, you should be able to convince yourself that's the case. There are probably other cases where you *don't* start at `read 2`, but this is the particular subset of traces that made it furthest in the history.

**Comment by Leviathan1995** [comment]
@aphyr Do you mean that because process 5 starts earlier than process 7, so the value of process 7 must be 2 or 3?

**Comment by aphyr** [comment]
No, that's not it. It's more that... you're correct in that this particular visualization, absent any other context, *is* linearizable. But if you look at what happened *before* this, you'll probably find that operations *prior* to this point prevent you from following the linearization you've described above. The visualization makes some tradeoffs in trying to show you a reasonably compact representation of the failure, and part of that is trusting that the traces it shows you are actually the furthest (uh, sort of) legal possibilities

 If you've used the timeline/html renderer, you should be able to click on the operations in linear.svg and it will take you right to that part of the history. Try scrolling back a bit and seeing the full thing in context.
