### ISSUE TITLE
how to set the duration of iptables?

### ISSUE THREAD

**Issue by Leviathan1995** [jepsen-io/jepsen#258]
@aphyr  I use the jepsen to test my system, but I think that the duration of iptables is too short. How to set the duration of iptables?  thanks!

**Comment by aphyr** [comment]
I'm sorry, I don't understand your question. What do you want to do?

**Comment by Leviathan1995** [comment]
@aphyr  Sorry, I mean that I want the network partition to be long enough.

**Comment by aphyr** [comment]
That's controlled by the generator you wrote as a part of your test.On May 5, 2018 11:13, Leviathan <notifications@github.com> wrote:@aphyr  Sorry, I mean that I want the network partition to be long enough.
