### ISSUE TITLE
The relationship between linearizability with the QPS？

### ISSUE THREAD

**Issue by Leviathan1995** [jepsen-io/jepsen#263]
@aphyr I use the jepsen to test my system, but now I wonder what the relationship between linearizability with the QPS？ In my opinion, the higher QPS return more operations over a period of time, and this situation is easy to happen unlinearizability ?

and how to use jepsen to test the sequential consistency and eventually consistency?

**Comment by aphyr** [comment]
It depends more on concurrency, size of the state space, and failure-vs-indeterminate categorization. This is a real long discussion, but I've written about it at length in past linearizability analyses, and in the tutorial.

**Comment by Leviathan1995** [comment]
@aphyr Thanks!  And how to use jepsen to test the sequential consistency and eventually consistency?

**Comment by aphyr** [comment]
There aren't generalized tests for either of those, but you can read the analyses for descriptions of other tests.

**Comment by Leviathan1995** [comment]
@aphyr I see what you mean. Thank you！
