### ISSUE TITLE
Is the jepsen add the network slow/fast of function is necessary?

### ISSUE THREAD

**Issue by Leviathan1995** [jepsen-io/jepsen#265]
@aphyr  The jepsen provides `fast!` and `slow!` in net module, but not provides a function like `
partition-random-halves`  to compose both of them. Do you think Is the jepsen add the `network-slow-fast` of the function is necessary?

**Comment by aphyr** [comment]
Not really; I never found those failure modes particularly useful.

**Comment by Leviathan1995** [comment]
ok!
