### ISSUE TITLE
Rare race condition in gen/time-limit

### ISSUE THREAD

**Issue by bdarnell** [jepsen-io/jepsen#268]
In the `catch` clauses of `gen/time-limit`, the current thread is removed from `@threads` before `@interrupted?` is examined:

https://github.com/jepsen-io/jepsen/blob/3b2442588df43396e39d2e79bef208da9f5327ab/jepsen/src/jepsen/generator.clj#L497-L505

When the stars align, the interrupting thread could awake from sleep, notice that `@threads` is empty and clear the `@interrupted?` flag.

https://github.com/jepsen-io/jepsen/blob/3b2442588df43396e39d2e79bef208da9f5327ab/jepsen/src/jepsen/generator.clj#L479-L484

I think this caused a spurious failure for us (cockroachdb/cockroach#26279). 

It looks to me that instead of an inner try/finally (with repeated assignments to `@threads` in the `catch` clauses), this cleanup could be done in one place in a `finally` for the top-level `try`, and this would avoid the race.

**Comment by aphyr** [comment]
Possssibly. There's definitely a race here, because I've seen this too. Definitely something that *needs* to be fixed, but I don't have time just now to hack on it--if you'd like to give your proposed fix a shot, go for it.

<sigh> interrupts... the literal worst :-O

**Comment by aphyr** [comment]
This is FINALLY done now that we have the new generator system in 0.1.19.
