### ISSUE TITLE
Error during nt/clock-nemesis setup on CentOS

### ISSUE THREAD

**Issue by ttyusupov** [jepsen-io/jepsen#271]
```
2018-06-01 20:33:01,888{GMT}    WARN    [jepsen nemesis] jepsen.core: Error setting up nemesis
java.util.concurrent.ExecutionException: java.lang.RuntimeException: sudo -S -u root bash -c "cd /; dpkg --get-selections build-essential" returned non-zero exit status 127 on yb-admin-timur-jepsen-06-01-n1. STDOUT:


STDERR:
bash: dpkg: command not found
```

`yum` should be used instead of `dpkg` on CentOS. I have a fix for that included in this commit - https://github.com/YugaByte/jepsen/commit/6c8a38ffdbcd64a441b66c8b69a5aee5ad3321e7#diff-a311b62d2e79e78232d992fbefa60255R169. I can extract related changed and submit a PR.

**Comment by ttyusupov** [comment]
After fixing "`dpkg` issue", faced another error:
```
ERROR [2018-06-01 20:47:59,371] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: java.lang.RuntimeException: sudo -S -u root bash -c "cd /; ntpdate -b pool.ntp.org" returned non-zero exit status 1 on yb-admin-timur-jepsen-06-01-n1. STDOUT:


STDERR:
 1 Jun 20:47:20 ntpdate[29067]: the NTP socket is in use, exiting
```

Maybe we need to stop NTP daemon at the nemesis start and start again at the nemesis stop?

**Comment by ttyusupov** [comment]
> Maybe we need to stop NTP daemon at the nemesis start and start again at the nemesis stop?
Or maybe even during OS setup/teardown calls since this is OS specific command?

**Comment by aphyr** [comment]
Hey, is this issue for Jepsen proper, or for your fork?

**Comment by ttyusupov** [comment]
I got this issue when using `nt/clock-nemesis` from official `[jepsen "0.1.9"]` with CentOS 7.4 on GCP.

**Comment by Leviathan1995** [comment]
@ttyusupov I find that you are using `[jepsen "0.1.9-SNAPSHOT"]`  not `[jepsen "0.1.9"]`

**Comment by ttyusupov** [comment]
@Leviathan1995 , I was using official `[jepsen "0.1.9"]` for this test, probably you found `[jepsen "0.1.9-SNAPSHOT"]` in our fork, but that is not what I was using for this test.

**Comment by Leviathan1995** [comment]
@ttyusupov `0.1.9` already supports Centos. Can you give me more details?

**Comment by ttyusupov** [comment]
@aphyr , Most of our customers are running CentOS in production, so that is the platform we've been using for Jepsen testing as well. In PR #275 I was able to get Nemesis working on CentOS without too many changes, and I think it would be useful for other users of Jepsen, too.

Actually, I had to implement `centos.clj` by myself a few weeks ago for our testing, but when I was merging your latest changes into our fork I've noticed that you also have `centos.clj` now. So, I've just extracted some updates from my version of `centos.clj` and that made your version of `centos.clj` at least work for now with GCP, but also had to update some other files (see PR).

**Comment by ttyusupov** [comment]
@aphyr , I have another update with changes localized in `jepsen.nemesis.time` which adds CentOS support - https://github.com/jepsen-io/jepsen/compare/master...YugaByte:fix-clock-nemesis-for-centos. If that works, I can submit it as a PR.

**Comment by aphyr** [comment]
The OS detection function you've got relies on the string representation of class names, which will break for anonymous classes. I recommend using feature detection, rather than trying to name OSes. Try to compile directly, if gcc's gone, fall back to apt, if that's absent, fall back to yum.

**Comment by ttyusupov** [comment]
Hi @aphyr , I've updated the fix - https://github.com/jepsen-io/jepsen/compare/master...YugaByte:fix-clock-nemesis-for-centos

**Comment by aphyr** [comment]
Looks good! I'd catch RuntimeException though; you might be interrupted here and you don't want to catch that; might cause deadlocks.

**Comment by ttyusupov** [comment]
I've updated exception type and created PR - https://github.com/jepsen-io/jepsen/pull/277
