### ISSUE TITLE
Can each node have its own role?

### ISSUE THREAD

**Issue by fengchuimailang** [jepsen-io/jepsen#283]
Can Jepsen test a cluster which has different roles?
eg: a cluster like mysql cluster which has both master and slaves.

**Comment by aphyr** [comment]
Yes.

**Comment by fengchuimailang** [comment]
I want to test a cluster of my company.   The cluster  which has 4 roles in it is hard to test for me.  I get confused.

Example of mysql cluster can not run.   Which example do you think can help me understand this situation？ I need your help. @aphyr

**Comment by aphyr** [comment]
Try the chronos tests.On Jul 31, 2018 22:16, fengchuimailang <notifications@github.com> wrote:I want to test a cluster of my company.   The cluster  which has 4 roles in it is hard to test for me.  I get confused.
Example of mysql cluster can not run.   Which example do you think can help me understand this situation？ I need your help. @aphyr
