### ISSUE TITLE
unmatched analysis result and op result sequence

### ISSUE THREAD

**Issue by qclu** [jepsen-io/jepsen#291]
I have tested my own distributed key-val store system. Following is part of analysis result:
--------------------------------------------------------------------------------
...
     :final-paths
     ([{:op
        {:process 3,
         :type :ok, 
         :f :write,
         :value 4,
         :index 283, 
         :time 50744211663},
        :model {:value 4}}
       {:op 
        {:process 9,
         :type :invoke,
         :f :read,
         :value 1,
         :index 285, 
         :time 50750856995},
        :model {:msg "can't read 1 from register 4"}}]
      [{:op
        {:process 3,
         :type :ok, 
         :f :write,
         :value 4,
         :index 283, 
         :time 50744211663},
        :model {:value 4}}
       {:op 
        {:process 7,
         :type :ok, 
         :f :read,
         :value 1,
         :index 286, 
         :time 50750935349},
        :model {:msg "can't read 1 from register 4"}}]),
...
--------------------------------------------------------------------------------
Next I check op seq in history.edn:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...
{:type :ok, :f :read, :value [0 1], :process 6, :time 50744166037, :index 282}
{:type :ok, :f :write, :value [0 4], :process 3, :time 50744211663, :index 283}
{:type :invoke, :f :read, :value [0 nil], :process 7, :time 50746213890, :index 284}
{:type :invoke, :f :read, :value [0 nil], :process 9, :time 50750856995, :index 285}
{:type :ok, :f :read, :value [0 1], :process 7, :time 50750935349, :index 286}
{:type :invoke, :f :write, :value [0 1], :process 7, :time 50754184241, :index 287}
{:type :ok, :f :read, :value [0 1], :process 9, :time 50755092795, :index 288}
{:type :invoke, :f :write, :value [0 0], :process 0, :time 50757594581, :index 289}
{:type :invoke, :f :write, :value [0 2], :process 8, :time 50758235688, :index 290}
{:type :ok, :f :write, :value [0 1], :process 7, :time 50758948486, :index 291}
{:type :invoke, :f :write, :value [0 3], :process 1, :time 50761289231, :index 292}
{:type :ok, :f :write, :value [0 0], :process 0, :time 50762394768, :index 293}
{:type :ok, :f :write, :value [0 2], :process 8, :time 50762940784, :index 294}
{:type :ok, :f :write, :value [0 3], :process 1, :time 50766157274, :index 295}
{:type :invoke, :f :write, :value [0 2], :process 5, :time 50766176024, :index 296}
{:type :invoke, :f :read, :value [0 nil], :process 4, :time 50768261685, :index 297}
{:type :ok, :f :write, :value [0 2], :process 5, :time 50771135891, :index 298}
{:type :ok, :f :read, :value [0 2], :process 4, :time 50773018366, :index 299}
...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

From above info, I get record 288, from read req issued from process 9, got value 1, but before it, record 287, process 7 already has invoked a write req and tried to write value 1.
So, I think this cannot infer the result ——"can't read 1 from register 4".
I am not sure it is correct or not I analyze so.
Would anyone give me some clues?
Thank u

**Comment by aphyr** [comment]
This knossos analysis ran out of linearizable options at 285 or 286, before reaching operation 287. I don't think operation 287 could play a role in this failure.--KyleOn Oct 24, 2018 07:09, Qichao <notifications@github.com> wrote:I have tested my own distributed key-val store system. Following is part of analysis result:
...
:final-paths
([{:op
{:process 3,
:type :ok,
:f :write,
:value 4,
:index 283,
:time 50744211663},
:model {:value 4}}
{:op
{:process 9,
:type :invoke,
:f :read,
:value 1,
:index 285,
:time 50750856995},
:model {:msg "can't read 1 from register 4"}}]
[{:op
{:process 3,
:type :ok,
:f :write,
:value 4,
:index 283,
:time 50744211663},
:model {:value 4}}
{:op
{:process 7,
:type :ok,
:f :read,
:value 1,
:index 286,
:time 50750935349},
:model {:msg "can't read 1 from register 4"}}]),
...
Next I check op seq in history.edn:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...
{:type :ok, :f :read, :value [0 1], :process 6, :time 50744166037, :index 282}
{:type :ok, :f :write, :value [0 4], :process 3, :time 50744211663, :index 283}
{:type :invoke, :f :read, :value [0 nil], :process 7, :time 50746213890, :index 284}
{:type :invoke, :f :read, :value [0 nil], :process 9, :time 50750856995, :index 285}
{:type :ok, :f :read, :value [0 1], :process 7, :time 50750935349, :index 286}
{:type :invoke, :f :write, :value [0 1], :process 7, :time 50754184241, :index 287}
{:type :ok, :f :read, :value [0 1], :process 9, :time 50755092795, :index 288}
{:type :invoke, :f :write, :value [0 0], :process 0, :time 50757594581, :index 289}
{:type :invoke, :f :write, :value [0 2], :process 8, :time 50758235688, :index 290}
{:type :ok, :f :write, :value [0 1], :process 7, :time 50758948486, :index 291}
{:type :invoke, :f :write, :value [0 3], :process 1, :time 50761289231, :index 292}
{:type :ok, :f :write, :value [0 0], :process 0, :time 50762394768, :index 293}
{:type :ok, :f :write, :value [0 2], :process 8, :time 50762940784, :index 294}
{:type :ok, :f :write, :value [0 3], :process 1, :time 50766157274, :index 295}
{:type :invoke, :f :write, :value [0 2], :process 5, :time 50766176024, :index 296}
{:type :invoke, :f :read, :value [0 nil], :process 4, :time 50768261685, :index 297}
{:type :ok, :f :write, :value [0 2], :process 5, :time 50771135891, :index 298}
{:type :ok, :f :read, :value [0 2], :process 4, :time 50773018366, :index 299}
...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
From above info, I get record 288, from read req issued from process 9, got value 1, but before it, record 287, process 7 already has invoked a write req and tried to write value 1.
So, I think this cannot infer the result ——"can't read 1 from register 4".
I am not sure it is correct or not I analyze so.
Would anyone give me some clues?
Thank u

**Comment by aphyr** [comment]
Look at :final-paths: those show you where the checker ran out of options.--KyleOn Oct 26, 2018 02:25, Qichao <notifications@github.com> wrote:@aphyr  thanks for your reply.
But I cannot really understand that "This knossos analysis ran out of linearizable options at 285 or 286, before reaching operation 287. ".
Would you please give some explanation in details?
