### ISSUE TITLE
How can I run test without dockers.

### ISSUE THREAD

**Issue by q96456** [jepsen-io/jepsen#293]
Can you give the specific process without  dockers.

**Comment by mkcp** [comment]
Hey @q96456, jepsen uses distinct machines to run its tests in an environment as close to real world use as possible. You can use physical machines, VMs, or containers. The docker script provides a straightforward way to set up containers for your test.

If you can describe what you're looking to accomplish w/ jepsen, we might be able to point you in a useful direction.
