### ISSUE TITLE
Question: Generating operations per-node

### ISSUE THREAD

**Issue by lyonssp** [jepsen-io/jepsen#357]
I am having trouble understanding the relationship between some processes and workers and the way generators can be defined in terms of them.

To start, I am trying to broadcast operations over my network at the start of my tests.  So I want to generate a single, targeted operation per node before my test logic starts.  I started with the `each` macro, but because that macro generates operation per-process, I see that new processes arrive throughout my test and yield operations from my generator unpredictably.

I have a few related questions:
* What is the significance of the logged identifiers here: `jepsen worker 0 - jepsen.util 4`?  Does a mismatch indicate that a new process has arrived at some point?
* Under what circumstance would a new process arrive in a test without a reported error
* Is there any support for generating operations per-node similar to the way `each` generates operations per-process?  

With respect to the last question, I'm currently settling for tagging operations with `:node` values and doing the routing in my clients, but would love to bury these details if possible to make my generators simpler.

**Comment by aphyr** [comment]
Would you mind pasting your generator here? I'd like a little more context before I give advice. :)

"Jepsen worker 0" means that it's the first worker thread. 4 is the message that thread logged. Was there more to this log line?

After the start of a test, new processes are created only when a process crashes with an :info message.

I don't think we have a per-node generator specifically, but you could certainly write one. You can derive node identifiers from either threads or processes via something like `(nth (:nodes test) (mod process node-count))`.

**Comment by lyonssp** [comment]
There was more to that log message, my apologies.  The original message looks like this:
` 2019-04-02 16:38:17,188{GMT}    INFO    [jepsen worker 0] jepsen.util: 4    :invoke :append nil`

More importantly though, this is what my generator looks like 
```
(ns smartlog.generator
   (:require [jepsen.generator :refer [op defgenerator]]))

 (defgenerator PerNode [gen memo]
   []
   (op [this test process]
       (let [head (first @memo)]
         (if head
           (do
             (swap! memo next)
             head)
           (let [op' (jepsen.generator/op gen test process)]
             (if (not op')
               op'
               (do
                 (compare-and-set! memo nil (map #(assoc op' :node %) (:nodes test)))
                 (jepsen.generator/op this test process))))))))

 (defn per-node
   [gen]
   "Generate operations yielded by gen once for each node"
   (PerNode. gen (atom nil)))```

It receives an op from an underlying generator, and in turn yields duplicates of that op with `:node` metadata for every node in the test definition
e.g.
```
(jepsen.generator/op
  (->> {:type :invoke :op :foo}
           (jepsen.generator/once)
           (per-node)) 
  jepsen.tests/noop-test 
  {:worker :process})

;; Yields the following in order
;; {:type :invoke :op :foo :node "n1"}
;; {:type :invoke :op :foo :node "n2"}
;; {:type :invoke :op :foo :node "n3"}
;; {:type :invoke :op :foo :node "n4"}
;; {:type :invoke :op :foo :node "n5"}
;; nil

The reason this isn't ideal is that I then have to coordinate this with my clients to route operations.  What I'm trying to do is hide that detail in the generator to simplify surrounding code.  I think the key question is: how do I create some kind of `process->node` mapping so that I can follow an approach more like the `each` generator?

**Comment by aphyr** [comment]
> 2019-04-02 16:38:17,188{GMT} INFO [jepsen worker 0] jepsen.util: 4 :invoke :append nil

Yes, this is an operation being logged. That message means "process 4 invoked an :f :append operation with :value nil."

For the generator, I'm a little confused here. I can tell you that there's a race condition here: you're returning the head after (swap! memo next), which won't be atomic with the swap! operation.

For the routing, I don't think you should need to do that in the client. Remember how I said earlier that you can get node IDs from processes? You can do that here, in the generator. :)

**Comment by lyonssp** [comment]
Going to close this, as I don't think I have any additional questions.

I've made some progress at this point, thanks!
