### ISSUE TITLE
How to make Jepsen workers read all keys

### ISSUE THREAD

**Issue by olegvelikanov** [jepsen-io/jepsen#384]
I am puzzled about how to write a generator for Jepsen test that will provide every worker with read ops of all keys in some range. 

For example, I have a cluster of 5 nodes and there are 5 keys written before and I have 5 workers (1 worker acting against 1 node). Now I want  each worker to read each key.

I tried this generator function but there were cases when last key (for example) was read 2 times by one worker and 0 times by another. I understand that this happens because of competing between workers for ops but I want generator doesn't give a read operation of key_x to worker_x if it has already given it to him.

```
(defn read_generator
  []
  (->>  (independent/sequential-generator
	      (range 5)
              (fn [k] (->> r (gen/limit 6))))
        (gen/nemesis nil)))
```

May be I have a general misunderstanding about Jepsen generator but I will be really grateful if you could help me and give some advice. Thank you  in advance.

**Comment by aphyr** [comment]
Without knowing what r is it's hard to say. If you wanted each worker to read keys, say, 0-4, in five different ops, one per key, I'd say:(->> (range 5)  (map (fn [x] {... :value x}))  gen/seq  gen/each)

**Comment by olegvelikanov** [comment]
> Without knowing what r is it's hard to say. If you wanted each worker to read keys, say, 0-4, in five different ops, one per key, I'd say:(->> (range 5)  (map (fn [x] {... :value x}))  gen/seq  gen/each)

Thanks a lot. That is exactly what i wanted to have. Looks like I missed gen/each function while scrolling generator.clj file.
