### ISSUE TITLE
nemesis/invoke! validation

### ISSUE THREAD

**Issue by stevana** [jepsen-io/jepsen#422]
I have a test in which I'd like to `step` the model when a particular nemesis operation happens.

When I tried the, to me, most obvious thing: returning a map with `:type :ok` in `nemesis/invoke!` I broke an assertion in `jepsen.core`:

```clojure
    ; Validate completion
    (assert (= (:type completion) :info)
            (str "Expected nemesis/invoke! to return a map with :type :ok, :fail, or :info, but received "
                 (pr-str completion) " instead"))
```

It seems to me that either the assert check or the message when the check fails is wrong. I hope it's the former, but I suspect it's the latter? Is there a good reason for only allowing `:info` here?

**Comment by aphyr** [comment]
The message is wrong; nemeses should always generate :info states. Jepsen assumes your model is invariant with respect to nemesis operations--that's kinda the whole point of nemeses: they shouldn't affect correctness. That doesn't stop you from using nemesis ops in an analysis, of course. You can write a checker to do that if you like. :)--KyleOn Oct 21, 2019 10:46, Stevan Andjelkovic <notifications@github.com> wrote:I have a test in which I'd like to step the model when a particular nemesis operation happens.
When I tried the, to me, most obvious thing: returning a map with :type :ok in nemesis/invoke! I broke an assertion in jepsen.core:
    ; Validate completion
    (assert (= (:type completion) :info)
            (str "Expected nemesis/invoke! to return a map with :type :ok, :fail, or :info, but received "
                 (pr-str completion) " instead"))
It seems to me that either the assert check or the message when the check fails is wrong. I hope it's the former, but I suspect it's the latter? Is there a good reason for only allowing :info here?
