### ISSUE TITLE
Question about donation code

### ISSUE THREAD

**Issue by RongtongJin** [jepsen-io/jepsen#425]
Hi Jepsen Community,

I wrote two jepsen tests about [openmessaging-storage-dledger](https://github.com/openmessaging/openmessaging-storage-dledger) and [apache rocketmq](https://github.com/apache/rocketmq).

DLedger is a raft-based commitlog, which could act as the persistent layer for distributed storage system. I used set checker to verify its consistency and fix the related bugs.
https://github.com/openmessaging/openmessaging-storage-dledger/pull/37
https://github.com/openmessaging/openmessaging-storage-dledger/pull/39

Apache RocketMQ is a distributed messaging and streaming platform. Since RocketMQ 4.5.0, RocketMQ supports the dledger deployment, like a raft-based  distributed message queue. I used total-queue checker to verify its consistency and fix the related bugs.
https://github.com/apache/rocketmq/issues/1464
https://github.com/apache/rocketmq/issues/1470

These have attracted some attention in the Apache RocketMQ community and openmessaging community. 

Some friends in the community asked me why there was no relevant code in jepsen repository, so could I submit the relevant code to jepsen repository?

**Comment by aphyr** [comment]
On 10/28/19 8:11 AM, rongtong wrote:
> Hi Jespen Community,
> 
> I wrote two jepsen tests about openmessaging-storage-dledger 
> <https://github.com/openmessaging/openmessaging-storage-dledger> and apache 
> rocketmq <https://github.com/apache/rocketmq>.

> Some friends in the community asked me why there was no relevant code in jepsen 
> repository, so could I submit the relevant code to jepsen repository?

You can submit PRs to the Jepsen repo, but I don't really see an advantage. 
Adding them to the Jepsen repo means I have to code-review everything you do, 
and that adds extra work and waiting for both of us.

If you'd like, you can also just make a PR adding a link from the Readme to your 
own repos. I've been meaning to add a "Other tests using Jepsen" link for a 
while now, and I do think it's nice to have a single place for discovery. :)

--Kyle

**Comment by vongosling** [comment]
@aphyr The code is in here https://github.com/openmessaging/openmessaging-dledger-jepsen.
