### ISSUE TITLE
Sequential execution of operations using a single client thread

### ISSUE THREAD

**Issue by stevana** [jepsen-io/jepsen#433]
Is there a way to sequential execute operations using only one client thread?

Given that having a valid sequential model is a prerequisite for checking if a concurrent history linearises, it seems useful to be able to do so. Not only would it make easier to debug the model/client/generators because there's no concurrency, but also because one could write a checker that outputs a trace, e.g. something like:

```
model0
  command0 => response0
model1
  command1 => response1
...
```

In the sequential case, crashing operations could short-circuit the execution which again would make it easier to debug as it gives us a faster feedback loop.

Lastly, being able to talk about the sequential case before introducing the concurrent one is probably helpful from an explanatory point of view.

Thoughts?

**Comment by aphyr** [comment]
Client threads perform every operation sequentially. If you want to run only one client thread, I think you can probably pass --concurrency 1 to Jepsen.

**Comment by stevana** [comment]
With `--concurrency 1` I still see concurrent histories e.g.:

```
{:type :ok, :f :increment, :value 1, ...}
{:type :ok, :f :increment, :value 4, ...}
{:type :ok, :f :increment, :value 5, ...}
{:type :ok, :f :increment, :value 3, ...}
{:type :ok, :f :increment, :value 2, ...}
```
where increment increments the value and returns it. What I would expect in the sequential case is that I get back the values 1-5 in order.

Maybe I'm not using the right terminology, perhaps what I want is only one worker?

**Comment by aphyr** [comment]
I just double-checked, and no, that definitely runs sequentially! Is it possible you're not threading the :concurrency option from the CLI into your test map?

**Comment by stevana** [comment]
My bad, you're right!

**Comment by aphyr** [comment]
Wooo! :)
