### ISSUE TITLE
lein run analyze straight after an analysis failure, doesn't reproduce the error

### ISSUE THREAD

**Issue by stevana** [jepsen-io/jepsen#440]
It seems that quite often if an analysis fails and I immediately after do `lein run analyze` I get a different error.

I would expect that `lein run analyze` analyses the same history that was just produced and that this analysis will result in the same failure as the first one, but perhaps this assumption is wrong?

I'm happy to try to produce a small example if that helps.

**Comment by aphyr** [comment]
Yeah, a repro case would be helpful here. What checker are you using? Sounds like maybe a serialization related issue?On Feb 19, 2020 08:05, Stevan Andjelkovic <notifications@github.com> wrote:It seems that quite often if an analysis fails and I immediately after do lein run analyze I get a different error.
I would expect that lein run analyze analyses the same history that was just produced and that this analysis will result in the same failure as the first one, but perhaps this assumption is wrong?
I'm happy to try to produce a small example if that helps.

**Comment by stevana** [comment]
I haven't been able to reproduce this. I'll reopen if I manage to.
