### ISSUE TITLE
MinIO (S3 compatible) Storage Support?

### ISSUE THREAD

**Issue by aadrian** [jepsen-io/jepsen#461]
Hi,

Would it be possible to test MinIO https://github.com/minio/minio with Jepsen ?
Or does this not make much sense for low level object storage?

Thank you.

**Comment by aphyr** [comment]
I don't see why not!On May 17, 2020 04:54, "Adrian A." <notifications@github.com> wrote:
Hi,
Would it be possible to test MinIO https://github.com/minio/minio with Jepsen ?
Or does this not make much sense for low level object storage?
Thank you.
