### ISSUE TITLE
Mismatch of no. of parameters in postgresql test

### ISSUE THREAD

**Issue by winddd** [jepsen-io/jepsen#467]
In [`jepsen.stolon.append`](https://github.com/jepsen-io/jepsen/blob/master/stolon/src/jepsen/stolon/append.clj#L154), it calls `await-open` with 2 parameters while in [`jepsen.stolon.client`](https://github.com/jepsen-io/jepsen/blob/master/stolon/src/jepsen/stolon/client.clj#L56), the function is defined to accept only one parameter.

The codes are attached here:
```
(do (when (zero? tries)
                  (throw e))
                (info "Retrying IO error")
                (Thread/sleep 1000)
                (c/close! conn)
                (retry (c/await-open test node)
                       (dec tries)))
```

```
(defn await-open
  "Waits for a connection to node to become available, returning conn. Helpful
  for starting up."
  [node]
  (with-retry [tries 100]
    (info "Waiting for" node "to come online...")
    (let [conn (open node)]
      (try (j/execute-one! conn
                           ["create table if not exists jepsen_await ()"])
           conn
           (catch org.postgresql.util.PSQLException e
             (condp re-find (.getMessage e)
               ; Ah, good, someone else already created the table
               #"duplicate key value violates unique constraint \"pg_type_typname_nsp_index\""
               conn

               (throw e)))))
    (catch org.postgresql.util.PSQLException e
      (when (zero? tries)
        (throw e))

      (Thread/sleep 5000)
      (condp re-find (.getMessage e)
        #"connection attempt failed"
        (retry (dec tries))

        #"Connection to .+ refused"
        (retry (dec tries))

        #"An I/O error occurred"
        (retry (dec tries))

        (throw e)))))
```

The `open` function has the similar issue when I am trying to run the postgresql test.

**Comment by aphyr** [comment]
Ah, whoops, that must have made it through my tests because the old arity was cached in the compiled namespace. Fixed!

**Comment by winddd** [comment]
It seems the codes haven't been updated yet. Will it be left in the next commit?


> Ah, whoops, that must have made it through my tests because the old arity was cached in the compiled namespace. Fixed!

**Comment by aphyr** [comment]
It's in origin now.

**Comment by winddd** [comment]
Similar case still exists in [db.clj](https://github.com/jepsen-io/jepsen/blob/master/stolon/src/jepsen/stolon/db.clj#L216) and [ledger.clj](https://github.com/jepsen-io/jepsen/blob/master/stolon/src/jepsen/stolon/ledger.clj#L108).

**Comment by winddd** [comment]
> Similar case still exists in [db.clj](https://github.com/jepsen-io/jepsen/blob/master/stolon/src/jepsen/stolon/db.clj#L216) and [ledger.clj](https://github.com/jepsen-io/jepsen/blob/master/stolon/src/jepsen/stolon/ledger.clj#L108).

But even if I deleted the argument `test` in these two places, it still doesn't work. There should be other places which call the `open` function  using reflection-mechanism-like methods？

Here are the logs：
![](https://raw.githubusercontent.com/winddt/ImageBed/master/img/20200630023252.png)

**Comment by winddd** [comment]
> Similar case still exists in [db.clj](https://github.com/jepsen-io/jepsen/blob/master/stolon/src/jepsen/stolon/db.clj#L216) and [ledger.clj](https://github.com/jepsen-io/jepsen/blob/master/stolon/src/jepsen/stolon/ledger.clj#L108).

But even if I deleted the two formal arguments `test` of `await-open` from these two files, it still doesn't work for `open` function. There should be other calls of `open` function in reflexive-mechanism-like ways I guess. 

Here is the screenshot:
![](https://raw.githubusercontent.com/winddt/ImageBed/master/img/20200630023252.png)
