### ISSUE TITLE
Proper way of inserting transaction history into Elle Checker

### ISSUE THREAD

**Issue by SungHoHong2** [jepsen-io/jepsen#483]
Hello Jepsen Developers,

My goal is to understand the proper use of `elle.list-append/check` to capture the anomalies from the transaction history.
I have currently finished the unit-testing experiment of Elle and want to proceed to test transaction anomalies using Redis and YugaByte.
I have noticed that after running the Redis-Raft, I get the `history.edn` file from `redis/store/redis 6.0.3 (raft e0123a9) append (test-type)` directory which consists of the history of transactions.
Am I expected to retrieve the **all histories** from `history.edn` and pass them as **a single argument** to the `elle.list-append/check` like this below?

```clojure
(:require [elle.list-append :as a])
(def history [ ... ])
(a/check {:consistency-models [:serializable], :directory "out"} history)
```

**Comment by aphyr** [comment]
No; this Jepsen test runs Elle automatically as a part of its analysis phase.On Aug 3, 2020 17:10, Sungho Hong <notifications@github.com> wrote:
Hello Jepsen Developers,
My goal is to understand the proper use of elle.list-append/check to capture the anomalies from the transaction history.
I have currently finished the unit-testing experiment of Elle and want to proceed to test transaction anomalies using Redis and YugaByte.
I have noticed that after running the Redis-Raft, I get the history.edn file from redis/store/redis 6.0.3 (raft e0123a9) append (test-type) directory which consists of the history of transactions.
Am I expected to retrieve the histories from history.edn and run the elle.list-append/check like this below?
(:require [elle.list-append :as a])
(def history [ ... ])
(a/check {:consistency-models [:serializable], :directory "out"} history)

**Comment by SungHoHong2** [comment]
@aphyr  Yes, but I am not sure where does the result from Elle is stored. 
From here, I do not see any consistency anomalies checked like the ones described in the Elle tutorial. 
```
/jepsen/redis/store/redis 6.0.3 (raft e0123a9) append /latest
-rw-r--r-- 1 root root 631568 Aug  3 20:48 history.edn
-rw-r--r-- 1 root root 291407 Aug  3 20:48 history.txt
-rw-r--r-- 1 root root 652056 Aug  3 20:48 jepsen.log
-rw-r--r-- 1 root root  18712 Aug  3 20:48 latency-quantiles.png
-rw-r--r-- 1 root root  25202 Aug  3 20:48 latency-raw.png
drwxr-xr-x 2 root root   4096 Aug  3 20:48 n1
drwxr-xr-x 2 root root   4096 Aug  3 20:48 n2
drwxr-xr-x 2 root root   4096 Aug  3 20:48 n3
drwxr-xr-x 2 root root   4096 Aug  3 20:48 n4
drwxr-xr-x 2 root root   4096 Aug  3 20:48 n5
-rw-r--r-- 1 root root  17165 Aug  3 20:48 rate.png
-rw-r--r-- 1 root root    525 Aug  3 20:48 results.edn
-rw-r--r-- 1 root root 294935 Aug  3 20:48 test.fressian
```

**Comment by aphyr** [comment]
See results.edn.On Aug 3, 2020 17:23, Sungho Hong <notifications@github.com> wrote:
@aphyr  Yes, but I am not sure where does the result from Elle is stored.
From here, I do not see any consistency anomalies checked like the ones described in the Elle tutorial.
/jepsen/redis/store/redis 6.0.3 (raft e0123a9) append /latest
-rw-r--r-- 1 root root 631568 Aug  3 20:48 history.edn
-rw-r--r-- 1 root root 291407 Aug  3 20:48 history.txt
-rw-r--r-- 1 root root 652056 Aug  3 20:48 jepsen.log
-rw-r--r-- 1 root root  18712 Aug  3 20:48 latency-quantiles.png
-rw-r--r-- 1 root root  25202 Aug  3 20:48 latency-raw.png
drwxr-xr-x 2 root root   4096 Aug  3 20:48 n1
drwxr-xr-x 2 root root   4096 Aug  3 20:48 n2
drwxr-xr-x 2 root root   4096 Aug  3 20:48 n3
drwxr-xr-x 2 root root   4096 Aug  3 20:48 n4
drwxr-xr-x 2 root root   4096 Aug  3 20:48 n5
-rw-r--r-- 1 root root  17165 Aug  3 20:48 rate.png
-rw-r--r-- 1 root root    525 Aug  3 20:48 results.edn
-rw-r--r-- 1 root root 294935 Aug  3 20:48 test.fressian
