### ISSUE TITLE
Any replacement to test wr-graph?

### ISSUE THREAD

**Issue by MICHAEL-ZENZ** [jepsen-io/jepsen#494]
Just testing the tidb with jepsen 2.0, it seems that wr-graph is no longer supported now. Is there any replacement for wr-graph?

**Comment by MICHAEL-ZENZ** [comment]
Oh I just found it in rw-register...

Sry for the trouble

**Comment by aphyr** [comment]
Yup! Sorry bout that--all this code wound up extracted into Elle, and the namespaces changed around a bit!
