### ISSUE TITLE
A contribution maybe useful

### ISSUE THREAD

**Issue by michaelzenz** [jepsen-io/jepsen#495]
Hi aphyr, I just wrote a test for postgres, utilizing the tests in TiDB. However, while writing it, I noticed that many of the codes can be reused, so I tried to work out a framework that minimize the extra code necessary to implement a test for a new database system, ease the burden for developers especially those who do not have knowledge about clojure and cannot afford the effort to learn it, but also want to use jepsen to test their database system. 

Can I just contribute it here?

**Comment by aphyr** [comment]
Possibly! We already have a postgres test, so there might be changes or additions to make there. If there are individual ease-of-use improvements which don't compromise generality, I'd like to make those changes to Jepsen itself. A nontrivial wrapper framework... that I'd suggest probably belongs as a separate library. That way you can maintain and deploy it yourself without waiting on me. :-)

**Comment by michaelzenz** [comment]
> Possibly! We already have a postgres test, so there might be changes or additions to make there. If there are individual ease-of-use improvements which don't compromise generality, I'd like to make those changes to Jepsen itself. A nontrivial wrapper framework... that I'd suggest probably belongs as a separate library. That way you can maintain and deploy it yourself without waiting on me. :-)

It`s not that big... Like for example, TiDB has much code that can be reused, including auto retries, start-and-wait. While these codes can be applied to a lot more dbms, it may not fit all distributed systems, which means these code should not be put into jepsen i suspect. And that`s why I wanna make a framework to reuse these code one layer above jepsen. It`s actually my intern project, so I need to have your permission first, but I guess it will be better for us to communicate with actual codes. It may take a few days to get through the process, will contact you until then.

**Comment by michaelzenz** [comment]
> Possibly! We already have a postgres test, so there might be changes or additions to make there. If there are individual ease-of-use improvements which don't compromise generality, I'd like to make those changes to Jepsen itself. A nontrivial wrapper framework... that I'd suggest probably belongs as a separate library. That way you can maintain and deploy it yourself without waiting on me. :-)

Hi aphyr, I just made a pull request, could you have a look at it?
