### ISSUE TITLE
Documentation for jepsen/docker

### ISSUE THREAD

**Issue by samarism** [jepsen-io/jepsen#496]
when trying to run ./up as written in readme.md; i get the following error:

```
./up: line 84: POSITIONAL[@]: unbound variable
```

**Comment by aphyr** [comment]
Maybe a shell thing?On Jan 22, 2021 05:48, Samarjit Uppal <notifications@github.com> wrote:
when trying to run ./up as written in readme.md; i get the following error:
./up: line 87: POSITIONAL[@]: unbound variable

**Comment by samarism** [comment]
Dont fully understand the use of POSITIONAL, For now i commented out the ```set -- "${POSITIONAL[@]}"``` line.

**Comment by aphyr** [comment]
Honestly not sure myself! @mkcp, your shell is better than mine--know what's up with this? I've just had some folks testing this on recent OS X builds and it seems to work for them, but not for @samarism.

**Comment by aphyr** [comment]
This is apparently a thing that happens with older versions of bash on OS X, and can be fixed by upgrading bash.
