### ISSUE TITLE
tar command in jepsen/docker/bin/up.sh does not work for Mac

### ISSUE THREAD

**Issue by samarism** [jepsen-io/jepsen#497]
Mac uses bsdtar by default which does not have the exclude-ignore flag. I had to install the gnu tar and update the bash file to use gtar instead.

**Comment by fwhdzh** [comment]
Thank you so much. Our laboratory is use only one server so it is inconvenient to modify the basic tool such as tar. It is pretty good if there are some platform-detection. Our OS version is CentOS 7.9.2009. By the way, in our OS, there is also a problem same as issue 496.
