### ISSUE TITLE
Documentation for jepsen.txn

### ISSUE THREAD

**Issue by zhangysh1995** [jepsen-io/jepsen#500]
Hi,

I want to see the internal of Jepsen how it works but could find limited resources on it.
I saw there is no generated documentation for `jepsen.txn`, is there any plan to add it?
If there are any resources I missed could you please point me to that?

Thank you.

**Comment by aphyr** [comment]
It's fairly small: only a few functions. Docstrings are in the source; see the txn directory.On Feb 24, 2021 00:48, Yushan ZHANG <notifications@github.com> wrote:
Hi,
I want to see the internal of Jepsen how it works but could find limited resources on it.
I saw there is no generated documentation for jepsen.txn, is there any plan to add it?
If there are any resources I missed could you please point me to that?
Thank you.
