### ISSUE TITLE
translate the jepsen doc with chinese language

### ISSUE THREAD

**Issue by jaydenwen123** [jepsen-io/jepsen#513]
We submit a pull request with title [translate the jepsen doc with chinese language](https://github.com/jepsen-io/jepsen/pull/510) a few days ago.

After I see the commented content in the closed pr. Then I take some time to make  a [online document](https://jaydenwen123.gitbook.io/zh_jepsen_doc/) with the translated content,the translated content we to maintain. And can you agree  to add the  link to the jepsen official docs to help other jepsen users to ease using jepsen ?

**link:** https://jaydenwen123.gitbook.io/zh_jepsen_doc/

**Comment by aphyr** [comment]
Done!
