### ISSUE TITLE
Exception in thread "main" Syntax error compiling at (jepsen/stolon/append.clj:1:1)

### ISSUE THREAD

**Issue by xxmy0825** [jepsen-io/jepsen#515]
jepsen version: 0.2.5

cd jepsen/stolon
lein run test-all -w append --nemesis none --max-writes-per-key 8 --node n1 --just-postgres --concurrency 50 -r 1000

which always prompts the following error, not sure what happened?
Exception in thread "main" Syntax error compiling at (jepsen/stolon/append.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)

**Comment by aphyr** [comment]
Did you make changes to the source?

**Comment by xxmy0825** [comment]
if i remember correctly, i didn't change it.

By the way, is there any quick way to verify if something wrong with the code, or something wrong with my operation method?

thanks

**Comment by aphyr** [comment]
I mean, this is a compilation error, so something's wrong with the code. What's confusing is that this definitely compiles for me, and you ought to be using the same version of Clojure... so I'm really at a loss here.

**Comment by xxmy0825** [comment]
sorry to trouble you, this problem should be caused by the error(like: xhost:  unable to open display "localhost:10.0") after it. at least after fixing the error, this problem doesn't exist.
