### ISSUE TITLE
Need an "import" in 04-checker.md

### ISSUE THREAD

**Issue by ajdavis** [jepsen-io/jepsen#520]
I'm using Clojure for the first time in order to work through the tutorial. Following instructions in the "Checking Correctness" section, I got:
```
Syntax error compiling deftype* at (jepsen/foo.clj:92:1).
Unable to resolve symbol: Model in this context
```
I think we need `(:import (knossos.model Model))` or something like that.

**Comment by aphyr** [comment]
That seems reasonable! Want to shoot over a PR?
