### ISSUE TITLE
Jepsen uses lazyfs repository that is not public available

### ISSUE THREAD

**Issue by ligurio** [jepsen-io/jepsen#534]
Commit effe3356438f2054294bf4b898fcf69777197f3f brings integration with lazyfs, but repository https://github.com/dsrhaslab/lazyfs.git is not available.

There are many similar fault-injection filesystems (see https://github.com/ligurio/unreliablefs#similar-projects), it would be interesting to know what is special in lazyfs.

**Comment by aphyr** [comment]
Calm dowwwwwwn, this is literally only hours old, already addressed in the commit message, and won't make its way into release for some time.On Apr 21, 2022 14:42, Sergey Bronnikov ***@***.***> wrote:
Commit effe335 brings integration with lazyfs, but repository https://github.com/dsrhaslab/lazyfs.git is not available.
There are many similar fault-injection filesystems (see https://github.com/ligurio/unreliablefs#similar-projects), it would be interesting to know what is special in lazyfs.

**Comment by ligurio** [comment]
Published - https://github.com/dsrhaslab/lazyfs.git
