### ISSUE TITLE
Replacing use of Clojure's random functions with a seedable PRNG?

### ISSUE THREAD

**Issue by cole-miller** [jepsen-io/jepsen#578]
As far as I can tell, there's no way to seed the clojure.core functions for making random choices (rand-int and co., see https://clojure.atlassian.net/browse/CLJ-1452), and this is annoying if you want to hold that particular source of nondeterminism fixed when running Jepsen to increase your chances of reproducing a bug. (Of course there are various other nondeterministic inputs into a Jepsen test run.) Would you be interested in a PR that replaced Jepsen's use of these functions with a seedable PRNG?

**Comment by aphyr** [comment]
I don't think this would be particularly useful--the scheduler, network, and database are all nondeterministic and concurrent.
