### ISSUE TITLE
net/fast runtime exception

### ISSUE THREAD

**Issue by as51340** [jepsen-io/jepsen#597]
I use jepsen.net package and its functions fast and slow. However, I am seeing this exception:

```
Error: Cannot delete qdisc with handle of zero.
```

Searched a bit and found this https://github.com/jepsen-io/jepsen/pull/541. Why it didn't get merged and how can I fix it?

My function:
```
(defn network-nemesis
  "Wraps a nemesis. Before underlying nemesis starts, slows the network by dt
  s. When underlying nemesis resolves, restores network speeds."
  [dt]
  (reify nemesis/Nemesis
    (setup! [this test]
      (net/fast! (:net test) test)
      this)

    (invoke! [_ test op]
      (case (:f op)
        :start (net/slow! (:net test) test {:mean (* dt 1000) :variance 1})

        :stop (net/fast! (:net test) test)))

    (teardown! [_ test]
      (net/fast! (:net test) test))))
```

I see in the docs packet-package but don't know how to use it, any advice?

**Comment by aphyr** [comment]
I'm not sure! @nurturenature was in there last--it looks like they closed the PR because they were making a bunch of other changes. It does sound like this is a bug in net/fast, so maybe this particular fix got lost in the shuffle. Want to put together a little PR?

**Comment by as51340** [comment]
yep sure!

**Comment by as51340** [comment]
@aphyr https://github.com/jepsen-io/jepsen/pull/598
