### ISSUE TITLE
/var/cache/apt/pkgcache.bin is missing in jespen debian container.

### ISSUE THREAD

**Issue by rameshvs02** [jepsen-io/jepsen#76]
Tried to duplicate SNAPSHOT ISOLATION issue (https://github.com/codership/galera/issues/336) on my local machine. But dirty-reads-test is exiting with file (/var/cache/apt/pkgcache.bin ) missing error in jespen debian containers. 

Local machine info : 
OS: Ubuntu 15.04

 Followed this for jespen download : https://github.com/aphyr/jepsen/tree/master/docker

root@aa912f8def96:/jepsen/galera# lein test

lein test jepsen.galera-test
INFO  jepsen.os.debian - :n3 setting up debian
INFO  jepsen.os.debian - :n4 setting up debian
INFO  jepsen.os.debian - :n1 setting up debian
INFO  jepsen.os.debian - :n2 setting up debian
INFO  jepsen.os.debian - :n5 setting up debian
INFO  jepsen.os.debian - Installing #{man-db curl iputils-ping logrotate sysvinit-core rsyslog faketime vim unzip wget iptables sysvinit}
INFO  jepsen.os.debian - Installing #{man-db curl iputils-ping logrotate sysvinit-core rsyslog faketime vim unzip wget iptables sysvinit}
INFO  jepsen.os.debian - Installing #{man-db curl iputils-ping logrotate sysvinit-core rsyslog faketime vim unzip wget iptables sysvinit}
INFO  jepsen.os.debian - Installing #{man-db curl iputils-ping logrotate sysvinit-core rsyslog faketime vim unzip wget iptables sysvinit}

lein test :only jepsen.galera-test/dirty-reads-test

ERROR in (dirty-reads-test) (FutureTask.java:122)
expected: (:valid? (:results (run! (dirty-reads/test- version 4))))
  actual: java.util.concurrent.ExecutionException: java.lang.RuntimeException: stat: cannot stat '/var/cache/apt/pkgcache.bin': No such file or directory

**Comment by aphyr** [comment]
Oh, we should catch and handle this in jepsen.os.debian--I think all you need is an apt-get update on each box to create the package cache.

**Comment by rameshvs02** [comment]
Executed apt-get update on each box but still package cache is not creating.

root@aa912f8def96:/jepsen/galera# docker ps
INFO[44134] GET /v1.17/containers/json                   
INFO[44134] +job containers()                            
INFO[44134] -job containers() = OK (0)                   
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
d260faf3687a        jepsennode:latest   "/run.sh"           12 hours ago        Up 12 hours                             n5                  
8b715eb5c8f9        jepsennode:latest   "/run.sh"           12 hours ago        Up 12 hours                             n4                  
98c01f0e597c        jepsennode:latest   "/run.sh"           12 hours ago        Up 12 hours                             n3                  
2e435b19b62d        jepsennode:latest   "/run.sh"           12 hours ago        Up 12 hours                             n2                  
d752bb5d9c6e        jepsennode:latest   "/run.sh"           12 hours ago        Up 12 hours                             n1                  
root@aa912f8def96:/jepsen/galera#  docker exec -it d752bb5d9c6e bash
INFO[44141] POST /v1.17/containers/d752bb5d9c6e/exec     
INFO[44141] +job execCreate(d752bb5d9c6e)                
INFO[44141] +job log(exec_create: bash , d752bb5d9c6e3785ae296a098b392c7cd24198f2dfabd54dfab0c231a0306b9b, jepsennode:latest) 
INFO[44141] -job log(exec_create: bash , d752bb5d9c6e3785ae296a098b392c7cd24198f2dfabd54dfab0c231a0306b9b, jepsennode:latest) = OK (0) 
INFO[44141] -job execCreate(d752bb5d9c6e) = OK (0)       
INFO[44141] POST /v1.17/exec/393e1c3d62fddce2d6f55fc2446837e3cc9683f41720f20f6097e3e63b2a5fac/start 
INFO[44141] +job execStart(393e1c3d62fddce2d6f55fc2446837e3cc9683f41720f20f6097e3e63b2a5fac) 
INFO[44141] +job log(exec_start: bash , d752bb5d9c6e3785ae296a098b392c7cd24198f2dfabd54dfab0c231a0306b9b, jepsennode:latest) 
INFO[44141] -job log(exec_start: bash , d752bb5d9c6e3785ae296a098b392c7cd24198f2dfabd54dfab0c231a0306b9b, jepsennode:latest) = OK (0) 
INFO[44141] POST /v1.17/exec/393e1c3d62fddce2d6f55fc2446837e3cc9683f41720f20f6097e3e63b2a5fac/resize?h=45&w=156 
INFO[44141] +job execResize(393e1c3d62fddce2d6f55fc2446837e3cc9683f41720f20f6097e3e63b2a5fac, 45, 156) 
INFO[44141] -job execResize(393e1c3d62fddce2d6f55fc2446837e3cc9683f41720f20f6097e3e63b2a5fac, 45, 156) = OK (0) 
root@d752bb5d9c6e:/# apt-get update                    
Hit http://security.debian.org jessie/updates InRelease
Get:1 http://security.debian.org jessie/updates/main amd64 Packages [174 kB] 
Ign http://httpredir.debian.org jessie InRelease      
Hit http://httpredir.debian.org jessie-updates InRelease 
Hit http://httpredir.debian.org jessie Release.gpg         
Get:2 http://httpredir.debian.org jessie-updates/main amd64 Packages [3614 B]
Hit http://httpredir.debian.org jessie Release  
Get:3 http://httpredir.debian.org jessie/main amd64 Packages [9035 kB]
Fetched 9213 kB in 27s (332 kB/s)                                                                                                                          
Reading package lists... Done
root@d752bb5d9c6e:/# ls -l /var/cache/apt/pkgcache.bin 
ls: cannot access /var/cache/apt/pkgcache.bin: No such file or directory
root@d752bb5d9c6e:/#

**Comment by dbpercona** [comment]
I have noticed that not all distributions of Debian/Ubuntu create the /var/cache/apt/pkgcache.bin  (tested in Docker).   I have seen the file on Ubuntu 15.x but not 14.x.    Perhaps there is another way of determining the last update time?

**Comment by hptabster** [comment]
Just saw this on Ubuntu 14.04 in an LXC.

**Comment by maoling** [comment]
I also saw this when run `cd aerospike & lein test`
version info:
`Linux version 3.10.0-327.22.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Jun 23 17:05:11 UTC 2016`

**Comment by aphyr** [comment]
Mao, you're running CentOS, but the Aerospike test is written for Debian, which is a different operating system. This is not something we can fix for you.
